
GET http://localhost:8081/locations
###

GET http://localhost:8081/locations/36
###
POST http://localhost:8081/locations
Content-Type:application/json

{
  "xCord": 22,
  "yCord": 22,
  "title": "test test test2",
  "info": "test test test2"
}

###

POST http://localhost:8081/users
Content-Type:application/json

{
  "email": "gcgp88test1@gmail.com",
  "username": "gcgp88test2",
  "password": "asdf1234",
  "passwordConfirm": "asdf1234"
}

###

POST http://localhost:8081/auth
Content-Type:application/json

{
  "username": "gcgp88test2",
  "password": "asdf1234"
}

###

DELETE http://localhost:8081/auth
Content-Type:application/json